### ISSUE TITLE
Tell with Sender?

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/gam#25]
Currently `Tell` does not pass any Sender to the target actor.
`Ask` on the other hand does, so that the asked actor can reply.

There are cases where one want to do an async Ask, that is, send a message with a sender, so the target actor can reply, but without blocking/waiting in the caller actor, where the response is just sent to the asking actor as a message.
`Ask` is a heavy operation, it will register a temp actorref in the process registry so that is not optimal for this kind of async operation.

How should we make it possible to Ask without a result, or Tell with a sender?

`AskAsync(msg, sender)`
`TellWithSender(msg, sender)`

Other suggestions?

cc @dtravin

**Comment by dtravin** [comment]
I think there is no real-life use of an Ask pattern, because it destroys the async nature of an event driven communication. There is no "request-response" concept, just lookup by ID and Tell.
If application really needs an async response then RPC or HTTP service looks much more suitable rather than asking an actor.

But we do need async in tests for convinience, so I would leave sender for Ask only.

**Comment by rogeralsing** [comment]
The current API now has `AskFuture` which is the blocking ask for tests, and `Ask` which only do a fire and forget `Tell` but with a sender, so the receiving actor can reply the same way as if it was called by `AskFuture`.
